public enum AgentState { 
    None,
    Exploring,
    GoingToWater,
    GoingToFood,
    GoingToNest,
    GoingToPartner,
    WaitingForPartner,
    Eating,
    Drinking,
    Resting,
    Fleeing,
    SearchingForMate,
    Reproducing,
}